# Generated by Django 3.1.3 on 2020-11-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='humedad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='temperatura',
            field=models.IntegerField(default=0),
        ),
    ]
