# Generated by Django 3.1.3 on 2020-11-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0002_auto_20201104_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='emai',
            new_name='email',
        ),
    ]
