# Generated by Django 3.1.4 on 2020-12-07 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0003_auto_20201105_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('rut', models.CharField(default=False, max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='password',
        ),
        migrations.AddField(
            model_name='medicion',
            name='foto',
            field=models.ImageField(null=True, upload_to='Fotos'),
        ),
        migrations.AddField(
            model_name='medicion',
            name='pila',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='predio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiREST.usuario')),
                ('cargo', models.CharField(default='', max_length=200, null=True)),
            ],
            bases=('apiREST.usuario',),
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('medicion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiREST.medicion')),
            ],
        ),
    ]
