# Generated by Django 3.1.4 on 2020-12-11 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0004_auto_20201207_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predio', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicion',
            name='predio',
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='unidad_medida',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='posicion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiREST.cliente'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='medicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiREST.pila'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='pila',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiREST.pila'),
        ),
    ]
