# Generated by Django 3.1.4 on 2021-01-15 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0005_auto_20201211_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lanza',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materiaprima',
            options={'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='pila',
            options={'ordering': ('cliente',)},
        ),
        migrations.RemoveField(
            model_name='lanza',
            name='cliente',
        ),
        migrations.AddField(
            model_name='pila',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiREST.cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
