# Generated by Django 3.1.4 on 2021-01-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0006_auto_20210115_0459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='materiaprima',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Materia Prima'},
        ),
        migrations.AlterModelOptions(
            name='medicion',
            options={'ordering': ('lanza',), 'verbose_name_plural': 'Mediciones'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=9),
        ),
    ]
