# Generated by Django 3.1.4 on 2021-01-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0007_auto_20210115_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='', max_length=15),
        ),
    ]
